development:
  adapter: postgresql
  encoding: utf8
  database: my_database_development
  pool: 5
  user: saneery
  password: 12asizez


test: 
  adapter: postgresql
  encoding: utf8
  database: my_database_test
  pool: 5
  user: saneery
  password: 12asizez


production:
  adapter: postgresql
  encoding: utf8
  database: my_database_production
  pool: 5
